require 'msgraph/odata/types/base_type'
require 'msgraph/odata/types/enum_type'
require 'msgraph/odata/types/primitive_types'
require 'msgraph/odata/types/complex_type'
require 'msgraph/odata/types/entity_type'
require 'msgraph/odata/types/collection_type'
